language: python

services:
  - docker

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true


# command to install dependencies
before_install:
  - pip install -U pip wheel
  - pip install -r requirements_extra_torch.txt
  # install tensorflow only in python 3.6, since lacking support for python 3.7
  # - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
  #     pip install -r requirements_extra_tf.txt;
  #     pip uninstall -y tensorflow-gpu;
  #     pip install tensorflow==1.12.0;
  #   fi
  - pip install -r requirements.txt
  - pip install codecov

install:
  - pip install .
# command to run tests
script:
  - pytest
  - codecov

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
