language: python

services:
  - docker

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true


# command to install dependencies
before_install:
  - pip install -U pip wheel
  - pip install -r requirements_extra_torch.txt
  - pip install -r requirements.txt
  - pip install codecov

install:
  - pip install .
# command to run tests
script:
  - pytest
  - codecov

