language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
 
 
# command to install dependencies
before_install:
  - pip install -U pip wheel
  - pip install torch
  - pip install -r requirements.txt
  
install:
  - pip install .
# command to run tests
script:
  - pytest

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  skip_existing: true
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    tags: true
