language: python

services:
  - docker

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true


# command to install dependencies
before_install:
  - pip install -U pip wheel
  - pip install -r requirements_extra_torch.txt
  - pip install -r requirements.txt
  - pip install codecov

install:
  - pip install .
# command to run tests
script:
  - pytest
  - codecov
 
after_success:
  # update latest docker image if on master branch, no pull request and latest python
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_PYTHON_VERSION" = "3.7" ]; then
      docker login -e $DOCKER_MAIL -u $DOCKER_USER -p $DOCKER_PW;
      docker build -t delira-full:latest docker/;
      docker tag delira-full:latest chrisha/delira-full:latest;
      docker push chrisha/delira-full:latest;
    fi
    
  # update tag image if latest python and valid tag
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.7" ] && [ "$TRAVIS_TAG" ]; then
      docker login -e $DOCKER_MAIL -u $DOCKER_USER -p $DOCKER_PW;
      docker build -t delira-full:$TRAVIS_TAG docker/;
      docker tag delira-full:$TRAVIS_TAG chrisha/delira-full:$TRAVIS_TAG;
      docker push chrisha/delira-full:$TRAVIS_TAG;
    fi
  
