language: python
python:
  - "3.6"
  - "3.7"
 
 
# command to install dependencies
before_install:
  - pip install -U pip wheel
  - pip install torch
  - pip install -r requirements.txt
  
install:
  - pip install .
# command to run tests
script:
  - pytest
