language: python

services:
  - docker

install:
  - docker build -t delira-py36:latest docker/ --build-arg python_version=3.6
  - docker build -t delira-py37:latest docker/ --build-arg python_version=3.7
script:
  - docker run delira-py36:latest /bin/sh -c "pytest delira/"
  - docker run delira-py37:latest /bin/sh -c "pytest delira/"

after_success:
  - docker login -e $DOCKER_MAIL -u $DOCKER_USER -p $DOCKER_PW
  - docker tag delira-py36:latest chrisha/delira-py36:latest
  - docker tag delira-py37:latest chrisha/delira-py37:latest
  - docker push chrisha/delira-py36:latest
  - docker push chrisha/delira-py37:latest
